### ISSUE TITLE
unhandledRejection: Channel ended, no reply will be forthcoming

### ISSUE THREAD

**Issue by carlosgeos** [swanest/micromessaging#44]
The test "stop listening should stay individual" and its after hook will sometimes fail with:

```
    ✓ should properly route requests to their corresponding handler (330ms)
    ✓ should stop listening (170ms)
unhandledRejection { Error: Channel ended, no reply will be forthcoming
    at rej (/app/node_modules/amqplib/lib/channel.js:195:7)
    at Channel.C._rejectPending (/app/node_modules/amqplib/lib/channel.js:197:28)
    at Channel.C.toClosed (/app/node_modules/amqplib/lib/channel.js:165:8)
    at Channel.accept (/app/node_modules/amqplib/lib/channel.js:184:12)
    at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/app/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  cause:
   Error: Channel ended, no reply will be forthcoming
       at rej (/app/node_modules/amqplib/lib/channel.js:195:7)
       at Channel.C._rejectPending (/app/node_modules/amqplib/lib/channel.js:197:28)
       at Channel.C.toClosed (/app/node_modules/amqplib/lib/channel.js:165:8)
       at Channel.accept (/app/node_modules/amqplib/lib/channel.js:184:12)
       at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:64:33)
       at Socket.go (/app/node_modules/amqplib/lib/connection.js:478:48)
       at Socket.emit (events.js:182:13)
       at emitReadable_ (_stream_readable.js:534:12)
       at process._tickCallback (internal/process/next_tick.js:63:19),
  isOperational: true }
unhandledRejection { Error: Channel ended, no reply will be forthcoming
    at rej (/app/node_modules/amqplib/lib/channel.js:195:7)
    at Channel.C._rejectPending (/app/node_modules/amqplib/lib/channel.js:197:28)
    at Channel.C.toClosed (/app/node_modules/amqplib/lib/channel.js:165:8)
    at Channel.accept (/app/node_modules/amqplib/lib/channel.js:184:12)
    at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/app/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  cause:
   Error: Channel ended, no reply will be forthcoming
       at rej (/app/node_modules/amqplib/lib/channel.js:195:7)
       at Channel.C._rejectPending (/app/node_modules/amqplib/lib/channel.js:197:28)
       at Channel.C.toClosed (/app/node_modules/amqplib/lib/channel.js:165:8)
       at Channel.accept (/app/node_modules/amqplib/lib/channel.js:184:12)
       at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:64:33)
       at Socket.go (/app/node_modules/amqplib/lib/connection.js:478:48)
       at Socket.emit (events.js:182:13)
       at emitReadable_ (_stream_readable.js:534:12)
       at process._tickCallback (internal/process/next_tick.js:63:19),
  isOperational: true }
    ✓ stop listening should stay individual (142ms)
    1) "after each" hook for "stop listening should stay individual"
  38 passing (44s)
  1 failing
  1) "after each" hook for "stop listening should stay individual":
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Observed twice on Node 12 and once on Node 8. Happens randomly, but always on this test.

**Comment by carlosgeos** [comment]
This should be reopened, happens on all versions randomly (but rarely)
